[phases.setup]
aptPkgs = ["wget", "bash", "curl"]

[phases.install]
cmds = [
  "npm ci",
  "chmod +x scripts/install-energyplus-render.sh",
  "./scripts/install-energyplus-render.sh"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_VERSION = "20.19.0"
