services:
  - type: web
    name: tropos3
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
