services:
  - type: web
    name: tropos3
    env: docker
    plan: free
    healthCheckPath: /api/health
    disk:
      name: tropos3-disk
      mountPath: /tmp
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ENERGYPLUS_PATH
        value: /usr/local/EnergyPlus-8-9-0/energyplus-8.9.0
