/**
 * Serviço para geração de arquivos IDF para o EnergyPlus
 */
import type { Dimensions, Materials } from '../types';

/**
 * Gera um arquivo IDF completo para o EnergyPlus com base nas dimensões do modelo,
 * ângulo do norte e materiais especificados.
 * 
 * @param dimensions - Dimensões da zona
 * @param northAngle - Ângulo do norte em radianos
 * @param materials - Materiais utilizados
 * @returns Conteúdo do arquivo IDF como string
 */
export const generateIdf = (
  dimensions: Dimensions, 
  northAngle: number, 
  materials: Materials
): string => {
  const { width, length, height } = dimensions;
  const northDeg = (northAngle * 180 / Math.PI) % 360;
  
  // Utilitário para formatar números
  const formatNum = (num: number): string => num.toFixed(6);
  
  // Calcular coordenadas da zona (centrada na origem)
  const x1 = -width/2;
  const x2 = width/2;
  const y1 = -length/2;
  const y2 = length/2;
  const z1 = 0;
  const z2 = height;
  
  // Mapear materiais para construções no EnergyPlus
  const wallConstruction = materials.wall === 'brick' ? 'Project wall' : 
                           materials.wall === 'concrete' ? 'Concrete Wall' :
                           materials.wall === 'wood' ? 'Wood Wall' : 'Project wall';
                           
  const windowConstruction = materials.window === 'single_clear' ? 'Single Clear' : 
                             materials.window === 'double_clear' ? '1001' : 'Single Clear';
                             
  const floorConstruction = materials.surface === 'tile' ? 'Project ground floor' : 
                           materials.surface === 'carpet' ? 'Floor Carpet' : 'Project ground floor';

  // Construir o arquivo IDF
  const idf = `! File generated by Tropos3D
! Generated automatically on ${new Date().toLocaleString()}

Version, 8.9.0.001;                               !- Version Identifier

RunPeriod,                                        !- Annual simulation
   Tropos3D Model,                                !- Location
   1,1,                                           !- Start Month , Day
   12,31,                                         !- End Month , Day
   UseWeatherFile,                                !- will use day as shown in weather file
   No,                                            !- Use weather file holidays/special day periods
   No,                                            !- Use WeatherFile DaylightSavingPeriod
   Yes,                                           !- Apply Weekend Holiday Rule
   Yes,                                           !- use weather file rain indicators
   Yes,                                           !- use weather file snow indicators
   1;                                             !- Number of years in simulation

Site:Location,Tropos3D Model,                     !- Location Name
   -23.55,                                        !- Latitude
   -46.64,                                        !- Longitude
   -3,                                            !- Time Zone
   720;                                           !- Elevation {m}

Site:GroundTemperature:BuildingSurface,           !- Annual ground temperatures
   18,18,18,18,18,18,18,18,18,18,18,18;           !- Monthly ground temperatures

SimulationControl,
   Yes,                                           !- Do the zone sizing calculation
   Yes,                                           !- Do the system sizing calculation
   No,                                            !- Do the plant sizing calculation
   No,                                            !- Do the design day calculation
   Yes;                                           !- Do the weather file calculation

SizingPeriod:DesignDay, Summer Design Day,        !- Design Day Name
   2,                                             !- Month
   21,                                            !- Day of Month
   SummerDesignDay,                               !- Day Type
   32.0,                                          !- Maximum Dry-Bulb Temperature {C}
   8.0,                                           !- Daily Dry-Bulb Temperature Range {C}
   ,                                              !- Dry-Bulb Temperature Range Modifier Type
   ,                                              !- Dry-Bulb Temperature Range Modifier Schedule
   WetBulb,                                       !- Humidity Condition Type
   25.0,                                          !- Wetbulb at Maximum Dry-Bulb{C}
   ,                                              !- Humidity Condition Day Schedule Name
   ,                                              !- Humidity Ratio at Maximum Dry-Bulb
   ,                                              !- Enthalpy Ratio at Maximum Dry-Bulb
   ,                                              !- Daily Wet-Bulb Temperature Range
   101217.,                                       !- Barometric Pressure {Pa}
   3.0,                                           !- Wind Speed {m/s}
   180,                                           !- Wind Direction {deg}
   No,                                            !- Rain Indicator
   No,                                            !- Snow Indicator
   Yes,                                           !- Daylight Saving Time Indicator
   ASHRAEClearSky,                                !- Solar Model Indicator
   ,                                              !- Beam Solar Day Schedule Name
   ,                                              !- Diffuse Solar Day Schedule Name
   ,                                              !- ASHRAE Clear Sky Optical Depth for Beam Irradiance (taub)
   ,                                              !- ASHRAE Clear Sky Optical Depth for Diffuse Irradiance (taud)
   1.0;                                           !- Sky Clearness

SizingPeriod:DesignDay, Winter Design Day,        !- Design Day Name
   7,                                             !- Month
   21,                                            !- Day of Month
   WinterDesignDay,                               !- Day Type
   18.0,                                          !- Maximum Dry-Bulb Temperature {C}
   8.0,                                           !- Daily Dry-Bulb Temperature Range {C}
   ,                                              !- Dry-Bulb Temperature Range Modifier Type
   ,                                              !- Dry-Bulb Temperature Range Modifier Schedule
   WetBulb,                                       !- Humidity Condition Type
   16.0,                                          !- Wetbulb at Maximum Dry-Bulb{C}
   ,                                              !- Humidity Condition Day Schedule Name
   ,                                              !- Humidity Ratio at Maximum Dry-Bulb
   ,                                              !- Enthalpy Ratio at Maximum Dry-Bulb
   ,                                              !- Daily Wet-Bulb Temperature Range
   101217.,                                       !- Barometric Pressure {Pa}
   2.0,                                           !- Wind Speed {m/s}
   0,                                             !- Wind Direction {deg}
   No,                                            !- Rain Indicator
   No,                                            !- Snow Indicator
   No,                                            !- Daylight Saving Time Indicator
   ASHRAEClearSky,                                !- Solar Model Indicator
   ,                                              !- Beam Solar Day Schedule Name
   ,                                              !- Diffuse Solar Day Schedule Name
   ,                                              !- ASHRAE Clear Sky Optical Depth for Beam Irradiance (taub)
   ,                                              !- ASHRAE Clear Sky Optical Depth for Diffuse Irradiance (taud)
   0.0;                                           !- Sky Clearness

Timestep, 2;                                      !- Timesteps/hour

ScheduleTypeLimits, Any Number;                   !- Not limited
ScheduleTypeLimits, Fraction,     0.0, 1.0, CONTINUOUS;
ScheduleTypeLimits, Temperature,  -60, 200, CONTINUOUS;

Schedule:Compact, 
      On,                                         !- Name
      Any Number,                                 !- Type
      Through: 12/31,                             !- Type
      For: AllDays,                               !- All days in year
      Until: 24:00,                               !- All hours in day
       1;     

Schedule:Compact, 
      Off,                                        !- Name
      Any Number,                                 !- Type
      Through: 12/31,                             !- Type
      For: AllDays,                               !- All days in year
      Until: 24:00,                               !- All hours in day
       0;

! Materials
Material, Concrete,
   Rough,                                         !- Roughness
   .1,                                            !- Thickness {m}
   1.13,                                          !- Conductivity {w/m-K}
   2000,                                          !- Density {kg/m3}
   1000,                                          !- Specific Heat {J/kg-K}
   0.9,                                           !- Thermal Emittance
   0.6,                                           !- Solar Absorptance
   0.6;                                           !- Visible Absorptance

Material, Brick,
   Rough,                                         !- Roughness
   .1,                                            !- Thickness {m}
   0.84,                                          !- Conductivity {w/m-K}
   1700,                                          !- Density {kg/m3}
   800,                                           !- Specific Heat {J/kg-K}
   0.9,                                           !- Thermal Emittance
   0.7,                                           !- Solar Absorptance
   0.7;                                           !- Visible Absorptance

WindowMaterial:Glazing,Clear3mm,                  !- Generic CLEAR 3MM
   SpectralAverage,                               !- Optical data type
   ,                                              !- Name of spectral data set
   .003,                                          !- Thickness {m}
   .837,                                          !- Solar transmittance at normal incidence
   .075,                                          !- Solar reflectance at normal incidence: front side
   .075,                                          !- Solar reflectance at normal incidence: back side
   .898,                                          !- Visible transmittance at normal incidence
   .081,                                          !- Visible reflectance at normal incidence: front side
   .081,                                          !- Visible reflectance at normal incidence: back side
   .0,                                            !- IR transmittance at normal incidence
   .84,                                           !- IR emissivity: front side
   .84,                                           !- IR emissivity: back side
   .9,                                            !- Conductivity {W/m-K}
   1;                                             !- Dirt Correction Factor

WindowMaterial:Gas,Air13mm,                       !- AIR 13MM
   Air,                                           !- Gas type
    .013;                                         !- Thickness {m}

! Constructions
Construction, Project wall,
   Brick;                                         !- Outside Layer

Construction, Project ground floor,
   Concrete;                                      !- Outside Layer

Construction, Single Clear,
   Clear3mm;                                      !- Outside Layer

Construction, 1001,                               !- Double glazing
   Clear3mm,                                      !- Outer glass
   Air13mm,                                       !- Air gap
   Clear3mm;                                      !- Inner glass

HeatBalanceAlgorithm, 
   ConductionTransferFunction,                    !- Heat Balance Algorithm
   2000,                                          !- Max Surface Temperature Limit
   0.00000001,                                    !- Minimum Surface Convection Heat Transfer Coefficient
   1000;                                          !- Maximum Surface Convection Heat Transfer Coefficient

ShadowCalculation, AverageOverDaysInFrequency, 20,  15000, SutherlandHodgman, SimpleSkyDiffuseModeling;

SurfaceConvectionAlgorithm:Inside,TARP;           !- Inside Convection Algorithm
SurfaceConvectionAlgorithm:Outside,DOE-2;         !- Outside Convection Algorithm

Building, Tropos3D Building,                     !- Building Name
   ${formatNum(northDeg)},                        !- North Axis
   Suburbs,                                       !- Terrain
    .04,                                          !- Loads Convergence Tolerance
    .4,                                           !- Temperature Convergence Tolerance
   FullExterior,                                  !- Solar Distribution
   25,                                            !- Maximum number of warmup days
   6;                                             !- Minimum number of warmup days

GlobalGeometryRules, LowerLeftCorner, CounterClockWise, Relative;

! Zone Definition
Zone, Zone Default,                               !- Zone Name
   0,                                             !- Relative North (to building)
   0,                                             !- X Origin (M)
   0,                                             !- Y Origin (M)
   0,                                             !- Z Origin (M)
   1 ,                                            !- Zone Type
   1,                                             !- Zone multiplier
   ,                                              !- Zone ceiling height
    ${formatNum(width * length * height)},        !- Zone volume
    ${formatNum(width * length)},                 !- Floor Area
   TARP,                                          !- Zone inside convection algorithm
   ,                                              !- Zone outside convection algorithm
   Yes;                                           !- Part Of Total Floor Area

! Ground floor
BuildingSurface:Detailed,                        !- Surface
   GroundFloor,                                   !- Surface name
   Floor, ${floorConstruction},                   !- Class and Construction Name
   Zone Default,                                  !- Zone Name
   Ground, ,                                      !- Outside Face Environment
   NoSun,                                         !- Sun Exposure
   NoWind,                                        !- Wind Exposure
   AutoCalculate,                                 !- View Factor to Ground
   4,                                             !- Number vertices
    ${formatNum(x1)}, ${formatNum(y1)}, ${formatNum(z1)},  !- Vertex 1
    ${formatNum(x2)}, ${formatNum(y1)}, ${formatNum(z1)},  !- Vertex 2
    ${formatNum(x2)}, ${formatNum(y2)}, ${formatNum(z1)},  !- Vertex 3
    ${formatNum(x1)}, ${formatNum(y2)}, ${formatNum(z1)};  !- Vertex 4

! Roof
BuildingSurface:Detailed,                        !- Surface
   Roof,                                          !- Surface name
   Roof, ${floorConstruction},                    !- Class and Construction Name
   Zone Default,                                  !- Zone Name
   Outdoors, ,                                    !- Outside Face Environment
   SunExposed,                                    !- Sun Exposure
   WindExposed,                                   !- Wind Exposure
   AutoCalculate,                                 !- View Factor to Ground
   4,                                             !- Number vertices
    ${formatNum(x1)}, ${formatNum(y1)}, ${formatNum(z2)},  !- Vertex 1
    ${formatNum(x1)}, ${formatNum(y2)}, ${formatNum(z2)},  !- Vertex 2
    ${formatNum(x2)}, ${formatNum(y2)}, ${formatNum(z2)},  !- Vertex 3
    ${formatNum(x2)}, ${formatNum(y1)}, ${formatNum(z2)};  !- Vertex 4

! Wall South (Y positive)
BuildingSurface:Detailed,                        !- Surface
   Wall South,                                    !- Surface name
   Wall, ${wallConstruction},                     !- Class and Construction Name
   Zone Default,                                  !- Zone Name
   Outdoors, ,                                    !- Outside Face Environment
   SunExposed,                                    !- Sun Exposure
   WindExposed,                                   !- Wind Exposure
   AutoCalculate,                                 !- View Factor to Ground
   4,                                             !- Number vertices
    ${formatNum(x2)}, ${formatNum(y2)}, ${formatNum(z1)},  !- Vertex 1
    ${formatNum(x1)}, ${formatNum(y2)}, ${formatNum(z1)},  !- Vertex 2
    ${formatNum(x1)}, ${formatNum(y2)}, ${formatNum(z2)},  !- Vertex 3
    ${formatNum(x2)}, ${formatNum(y2)}, ${formatNum(z2)};  !- Vertex 4

! Window South
FenestrationSurface:Detailed, Window South,      !- Window name
   Window,                                        !- Class
   ${windowConstruction},                         !- Construction Name
   Wall South,                                    !- Base surface
   ,                                              !- corresponding other window subsurface
   AutoCalculate,                                 !- View Factor to Ground
   ,                                              !- Window shading control
   ,                                              !- Frame divider name
   1,                                             !- Multiplier
   4,                                             !- Number vertices
    ${formatNum(-0.75)}, ${formatNum(y2)}, ${formatNum(0.84)},   !- Vertex 1
    ${formatNum(0.75)}, ${formatNum(y2)}, ${formatNum(0.84)},    !- Vertex 2
    ${formatNum(0.75)}, ${formatNum(y2)}, ${formatNum(2.26)},    !- Vertex 3
    ${formatNum(-0.75)}, ${formatNum(y2)}, ${formatNum(2.26)};   !- Vertex 4

! Wall North (Y negative)
BuildingSurface:Detailed,                        !- Surface
   Wall North,                                    !- Surface name
   Wall, ${wallConstruction},                     !- Class and Construction Name
   Zone Default,                                  !- Zone Name
   Outdoors, ,                                    !- Outside Face Environment
   SunExposed,                                    !- Sun Exposure
   WindExposed,                                   !- Wind Exposure
   AutoCalculate,                                 !- View Factor to Ground
   4,                                             !- Number vertices
    ${formatNum(x1)}, ${formatNum(y1)}, ${formatNum(z1)},  !- Vertex 1
    ${formatNum(x2)}, ${formatNum(y1)}, ${formatNum(z1)},  !- Vertex 2
    ${formatNum(x2)}, ${formatNum(y1)}, ${formatNum(z2)},  !- Vertex 3
    ${formatNum(x1)}, ${formatNum(y1)}, ${formatNum(z2)};  !- Vertex 4

! Window North
FenestrationSurface:Detailed, Window North,      !- Window name
   Window,                                        !- Class
   ${windowConstruction},                         !- Construction Name
   Wall North,                                    !- Base surface
   ,                                              !- corresponding other window subsurface
   AutoCalculate,                                 !- View Factor to Ground
   ,                                              !- Window shading control
   ,                                              !- Frame divider name
   1,                                             !- Multiplier
   4,                                             !- Number vertices
    ${formatNum(0.75)}, ${formatNum(y1)}, ${formatNum(0.84)},    !- Vertex 1
    ${formatNum(-0.75)}, ${formatNum(y1)}, ${formatNum(0.84)},   !- Vertex 2
    ${formatNum(-0.75)}, ${formatNum(y1)}, ${formatNum(2.26)},   !- Vertex 3
    ${formatNum(0.75)}, ${formatNum(y1)}, ${formatNum(2.26)};    !- Vertex 4

! Wall East (X positive)
BuildingSurface:Detailed,                        !- Surface
   Wall East,                                     !- Surface name
   Wall, ${wallConstruction},                     !- Class and Construction Name
   Zone Default,                                  !- Zone Name
   Outdoors, ,                                    !- Outside Face Environment
   SunExposed,                                    !- Sun Exposure
   WindExposed,                                   !- Wind Exposure
   AutoCalculate,                                 !- View Factor to Ground
   4,                                             !- Number vertices
    ${formatNum(x2)}, ${formatNum(y1)}, ${formatNum(z1)},  !- Vertex 1
    ${formatNum(x2)}, ${formatNum(y2)}, ${formatNum(z1)},  !- Vertex 2
    ${formatNum(x2)}, ${formatNum(y2)}, ${formatNum(z2)},  !- Vertex 3
    ${formatNum(x2)}, ${formatNum(y1)}, ${formatNum(z2)};  !- Vertex 4

! Window East
FenestrationSurface:Detailed, Window East,       !- Window name
   Window,                                        !- Class
   ${windowConstruction},                         !- Construction Name
   Wall East,                                     !- Base surface
   ,                                              !- corresponding other window subsurface
   AutoCalculate,                                 !- View Factor to Ground
   ,                                              !- Window shading control
   ,                                              !- Frame divider name
   1,                                             !- Multiplier
   4,                                             !- Number vertices
    ${formatNum(x2)}, ${formatNum(-0.75)}, ${formatNum(0.84)},   !- Vertex 1
    ${formatNum(x2)}, ${formatNum(0.75)}, ${formatNum(0.84)},    !- Vertex 2
    ${formatNum(x2)}, ${formatNum(0.75)}, ${formatNum(2.26)},    !- Vertex 3
    ${formatNum(x2)}, ${formatNum(-0.75)}, ${formatNum(2.26)};   !- Vertex 4

! Wall West (X negative)
BuildingSurface:Detailed,                        !- Surface
   Wall West,                                     !- Surface name
   Wall, ${wallConstruction},                     !- Class and Construction Name
   Zone Default,                                  !- Zone Name
   Outdoors, ,                                    !- Outside Face Environment
   SunExposed,                                    !- Sun Exposure
   WindExposed,                                   !- Wind Exposure
   AutoCalculate,                                 !- View Factor to Ground
   4,                                             !- Number vertices
    ${formatNum(x1)}, ${formatNum(y2)}, ${formatNum(z1)},  !- Vertex 1
    ${formatNum(x1)}, ${formatNum(y1)}, ${formatNum(z1)},  !- Vertex 2
    ${formatNum(x1)}, ${formatNum(y1)}, ${formatNum(z2)},  !- Vertex 3
    ${formatNum(x1)}, ${formatNum(y2)}, ${formatNum(z2)};  !- Vertex 4

! Window West
FenestrationSurface:Detailed, Window West,       !- Window name
   Window,                                        !- Class
   ${windowConstruction},                         !- Construction Name
   Wall West,                                     !- Base surface
   ,                                              !- corresponding other window subsurface
   AutoCalculate,                                 !- View Factor to Ground
   ,                                              !- Window shading control
   ,                                              !- Frame divider name
   1,                                             !- Multiplier
   4,                                             !- Number vertices
    ${formatNum(x1)}, ${formatNum(0.75)}, ${formatNum(0.84)},    !- Vertex 1
    ${formatNum(x1)}, ${formatNum(-0.75)}, ${formatNum(0.84)},   !- Vertex 2
    ${formatNum(x1)}, ${formatNum(-0.75)}, ${formatNum(2.26)},   !- Vertex 3
    ${formatNum(x1)}, ${formatNum(0.75)}, ${formatNum(2.26)};    !- Vertex 4

! Outputs
Output:Variable, *, Zone Mean Air Temperature, hourly, ;
Output:Variable, *, Zone Mean Radiant Temperature, hourly, ;
Output:Variable, *, Zone Air Relative Humidity, hourly, ;
Output:Variable, *, Site Outdoor Air Drybulb Temperature, hourly;

Output:Surfaces:Drawing, DXF, Triangulate3DFace;
OutputControl:ReportingTolerances,1.11,1.11;
`;

  return idf;
};
